# Generated by Django 6.0.3 on 2026-04-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonat_app', '0003_user_telegram_id_telegramconnection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sonat_app/telegram_bot/data/audio_files')),
                ('cover_file', models.FileField(blank=True, null=True, upload_to='sonat_app/telegram_bot/data/cover_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='telegramconnection',
            name='valid',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.DeleteModel(
            name='UploadedMedia',
        ),
    ]
